### ISSUE TITLE
pyTigerGraph Installed Query Integration

### ISSUE THREAD

**Issue by ewimp1** [tigergraph/pyTigerGraph#135]
It would be good to view the text of an installed query via pyTigerGraph, e.g., 

>>conn.printInstalledQuery("your_query_name")
>>"""CREATE QUERY your_query_name(*/params*/) {
...
}
"""

This would help as I have my query version-controlled in a separate library to my TG server. Hence I could check the TG installed query and my version match before running.

**Comment by parkererickson-tg** [comment]
Thanks for the suggestion @ewimp1! I will add this to our backlog.

**Comment by parkererickson-tg** [comment]
A temporary solution: 

```
conn.gsql("USE GRAPH graph_name SHOW QUERY query_name")
```
