### ISSUE TITLE
Streamlit Connection integration

### ISSUE THREAD

**Issue by sfc-gh-jcarroll** [tigergraph/pyTigerGraph#156]
**Is your feature request related to a problem? Please describe.**
Streamlit team recently released [st.experimental_connection](https://blog.streamlit.io/introducing-st-experimental_connection/) to make connecting to data stores even easier. Previously, @GenericP3rson had built a TigerGraph tutorial for Streamlit as it sounded like these were commonly used together. https://github.com/streamlit/docs/pull/121

**Describe the solution you'd like**
Wanted to see if TigerGraph team wanted to build a connection implementation for Streamlit and update the existing tutorial to use this.

**Describe alternatives you've considered**
Continue with the existing tutorial, which is great 😄 

**Additional context**

Connections can be built by extending [ExperimentalBaseConnection](https://docs.streamlit.io/library/api-reference/connections/st.connections.experimentalbaseconnection). We've built a few examples:

- https://github.com/streamlit/files-connection
- https://github.com/streamlit/gsheets-connection
- https://github.com/streamlit/release-demos/blob/master/1.22/st-experimental-connection/duckdb_connection/connection.py

If someone is interested in taking this on and setting up the repo, would be happy to discuss, do code review, or set up a quick call to discuss. If not no worries (and feel free to close this). Cheers!

**Comment by parkererickson-tg** [comment]
Thanks for the info @sfc-gh-jcarroll ! Looks like a good potential enhancement. Definitely will discuss with the team.
