### ISSUE TITLE
query result empty in  runInstalledQuery async mode

### ISSUE THREAD

**Issue by AbhishekOnedigital** [tigergraph/pyTigerGraph#195]
I am trying to run a query in async mode if i am running without async mode it works fine but in async mode empty status is coming 

```python 
result_2=conn.runInstalledQuery('getusersummary',params, timeout=360000 ,runAsync=True)
conn.checkQueryStatus('16777219.RESTPP_1_1.1697192938910.N')

```
![image](https://github.com/tigergraph/pyTigerGraph/assets/17587331/234618dc-de1c-4057-8644-4466c37a40f2)

you can see in screenshot is result is empty array

**Comment by parkererickson-tg** [comment]
Hi @AbhishekOnedigital - thanks for the report. Can you provide the version of pyTigerGraph and of the TigerGraph database you are using? 

Also, what happens if you try to retrieve the result via `conn.getQueryResult()`?

Thanks!

**Comment by AbhishekOnedigital** [comment]
Hi @parkererickson-tg 

Tiger graph version - 3.9.2
Pytigergraph - 1.4.1

![image](https://github.com/tigergraph/pyTigerGraph/assets/17587331/f77aa7f6-20ed-42f7-9728-900c9beee591)

**Comment by parkererickson-tg** [comment]
Hmmm. This seems to be an issue with the database most likely. Do you have access to our Zendesk?

**Comment by AbhishekOnedigital** [comment]
what is zendesk can you help me with link ?

till yesterday it was working . without async parameter it is working 

Thanks @parkererickson-tg

**Comment by parkererickson-tg** [comment]
https://www.tigergraph.com/support/ should point you to the correct place depending on the product you are using. Chances are that this will run across my plate internally again, but it does appear to be a database issue to me right now.
