### ISSUE TITLE
v 1.6.1 breaks delete API

### ISSUE THREAD

**Issue by BezBartek** [tigergraph/pyTigerGraph#223]
Version 1.6.1 adds to method `_delete` new keyword, `resKey` with different default (`None`), than `_req` method has (`"results"`). That of course would break API, and forces to provide `"results"` as `resKey` parameter, to make _delete work.  But `delVerticesById` that wraps `_delete` do not inherit that interface (it doesn't accept `resKey` param). So in fact, you no longer can use `delVerticesById` (Key error! cuz there is no `deleted_vertices` in response dict)
- It is wrong default on `_delete` method, it should be exactly same as on _req.
- It is unclear, why _delete method has that parameter anyway. I would advise dropping it.

**Comment by parkererickson-tg** [comment]
Resolved in v1.6.2
