### ISSUE TITLE
Error when creating a token with pyTigerGraph 1.7.2 on TG server V 3.10.1

### ISSUE THREAD

**Issue by custom-discoveries** [tigergraph/pyTigerGraph#255]
**Describe the bug**
It seems that under pyTigerGraph 1.7.2 I'm unable to create a token. I'm receiving the the following error:
HTTPError('404 Client Error: Not Found for url: https://c5cc0e0a08314d139c8e007bfaf9486e.i.tgcloud.io:443/restpp/v1/tokens')

**To Reproduce**
1. Install pyTigerGraph 1.7.2
2. Connect to TigerGraph iCloud Sever 3.10.1
3. Create Secret
4. Then Create a Token with Secret
5. See error

**Expected behavior**
If I run pyTigerGraph 1.7.0 everything works fine.

**Screenshots**
None

**Desktop (please complete the following information):**
 - MacOS: 12.7.6
 - Browser Microsoft Edge 
 - Version Edge 129.0.2792.65 (Official build) (x86_64)

**Smartphone (please complete the following information):**
- NA

**Additional context**
Looks like 1.7.2 is not backwards compatible with TigerGraph 3.10.1

**Comment by parkererickson-tg** [comment]
Thank you for the bug report, we will work to resolve ASAP.

**Comment by parkererickson-tg** [comment]
Released fix in v1.7.3, upgrade with `pip install -U pyTigerGraph`
