### ISSUE TITLE
Enhance GSQL LS command to allow specific display of database features

### ISSUE THREAD

**Issue by demit733** [tigergraph/pyTigerGraph#44]
**Is your feature request related to a problem? Please describe.**
Currently when executing the gsql LS command, the output provides a status report on Vertices, Edges, Graphs, Jobs Queries and Tags, all in one display. 

**Describe the solution you'd like**
It would be nice to have the gsql LS command have the ability to pass options to only display the specific area of interest.
Ideally, the gsql LS command would support the options such as: -v  (Vertices), -e (Edges), -g (Graphs) -j (Jobs), -q (Queries), -t (Tags)  to only show just the specific area of interest. 

Examples:
gsql use graph myGraph ls -v
Vertex Types:
- only Vertex's displayed here...

gsql use graph myGraph ls -q
Queries:
- only Queries displayed here...

gsql ls -g
Graphs:
- dispaly all graphs defined in database

**Describe alternatives you've considered**
None Identified

**Additional context**
I believe other users have asked for capabilities to have a global view of all graphs only, and not display all the other features of that database.

**Comment by parkererickson** [comment]
Thanks for your suggestion @demit733! I am going to close this issue, as this is something that should be implemented at the core database level rather than pyTigerGraph. I will certainly pass the feature request along to the team though.
